server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1026473353732-u30hjtlt3m2tqtgskfkjvfuui7b2dhnj.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          kakao:
            clientId: 56d09a99166663377127ddfe23e5da2d
#            client-secret: X24Mk2OY2Q64lBremvechLyEif2hcLzl
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
            clientAuthenticationMethod: POST
            clientName: kakao

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/hada_svc?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjddlsdnr12!
    hikari:
      minimum-idle: 30
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  #  group-configs:
  #    - group: v1
  #      paths-to-match: /api/v1/**
  #    - group: test
  #      paths-to-match: /api/test/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    enabled: false
    operations-sorter: method
    persist-authorization: true
    path: /hada/swagger-ui.html
    groups-order: desc



jwt:
  token:
    secretKey: 5NfkSiBIUH7cD7iDYlAMzfPoX6T7ryPX
    expTime: 86400000


