server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hada_svc?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

springdoc:
  swagger-ui:
    enabled: true
    persist-authorization: true